name-template: 'v${{ inputs.version }} For Minecraft 1.17, 1.18, 1.19.3 and 1.20.1'
tag-template: 'v${{ inputs.version }}'
template: |
  ## Change Log
            
  $CHANGES
prerelease: ${{ contains('alpha', inputs.release_type) || contains('beta', inputs.release_type) }}
