# Fabric Properties
	# check these on https://fabricmc.net/versions.html?&version=1.20.1
	minecraft_version=26.1

# Fabric Mod Metadata
	minecraft_requirement_version=26.1.x
	carpet_requirement_version=>=1.4.147

# Build Information
	# The target mc versions for the mod during mod publishing, separated with \n
	game_versions=26.1

# Dependencies
	fabric_version=0.145.1+26.1
	carpet_core_version=v26.1

